version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      # 使用更精确的挂载方式，避免挂载冲突
      - ./app:/www/app
      - ./bootstrap:/www/bootstrap
      - ./config:/www/config
      - ./database:/www/database
      - ./public:/www/public
      - ./resources:/www/resources
      - ./routes:/www/routes
      - ./storage:/www/storage
      # u79fbu9664u5bf9 composer.json u548c composer.lock u6587u4ef6u7684u6302u8f7du4ee5u907fu514du51b2u7a81
      - ./.docker/.data/redis/:/data/
    environment:
      - docker=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
    depends_on:
      - redis
    restart: on-failure
    ports:
      - 7001:7001
    networks:
      - xboard-network

  horizon:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      # 使用更精确的挂载方式，避免挂载冲突
      - ./app:/www/app
      - ./bootstrap:/www/bootstrap
      - ./config:/www/config
      - ./database:/www/database
      - ./public:/www/public
      - ./resources:/www/resources
      - ./routes:/www/routes
      - ./storage:/www/storage
      # u79fbu9664u5bf9 composer.json u548c composer.lock u6587u4ef6u7684u6302u8f7du4ee5u907fu514du51b2u7a81
      - ./.docker/.data/redis/:/data/
    restart: on-failure
    command: php artisan horizon
    depends_on:
      - redis
    networks:
      - xboard-network

  redis:
    image: redis:7-alpine
    command: redis-server --port 6379 --save 900 1 --save 300 10 --save 60 10000
    restart: unless-stopped
    volumes:
      - ./.docker/.data/redis:/data
    networks:
      - xboard-network

networks:
  xboard-network:
    driver: bridge